# Generated by Django 3.2.4 on 2021-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('unity', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('moreDesc', models.CharField(max_length=200)),
                ('dispo', models.IntegerField()),
            ],
        ),
    ]
