# Generated by Django 3.2.4 on 2021-07-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date',
            new_name='dateCommande',
        ),
    ]
